name: Build

on:
  push:

jobs:
  docker:
    strategy:
      matrix:
        version: [1.87.0]
        variant: [debug, release]
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: iantorres/compiler:${{ matrix.version }}-${{ matrix.variant }}
          build-args: |
            BOOST_VERSION=${{ matrix.version }}
            BOOST_VARIANT=${{ matrix.variant }}